#!/usr/bin/env python3
"""Tworzy logo startowe jadra Linuksa z branding/onemax-logo.png.

Jadro (CONFIG_LOGO_LINUX_CLUT224) czyta tylko tekstowy format PPM (P3), binarny P6
nie jest obslugiwany przez drivers/video/logo/pnmtologo.c. Logo jest skladane na czarnym
tle, bo konsola framebuffer jest czarna.

Uzycie:
    python3 scripts/make-kernel-logo.py --out build/logo_linux_clut224.ppm
"""

import argparse
from pathlib import Path

from PIL import Image

REPO = Path(__file__).resolve().parent.parent


def main() -> None:
    parser = argparse.ArgumentParser(description="Logo OneMax dla jadra (PPM P3).")
    parser.add_argument("--src", default=str(REPO / "branding" / "onemax-logo.png"))
    parser.add_argument("--out", required=True, help="sciezka wyjsciowa .ppm")
    parser.add_argument("--width", type=int, default=320, help="szerokosc w pikselach")
    args = parser.parse_args()

    src = Image.open(args.src).convert("RGBA")
    width = args.width
    height = round(src.height * width / src.width)

    black = Image.new("RGBA", src.size, (0, 0, 0, 255))
    flat = Image.alpha_composite(black, src).convert("RGB")
    small = flat.resize((width, height), Image.Resampling.LANCZOS)
    # pnmtologo (clut224) przyjmuje najwyzej 224 kolory: redukujemy palete (jak ppmquant).
    small = small.quantize(colors=224, method=Image.Quantize.MEDIANCUT).convert("RGB")
    raw = small.tobytes()  # RGB, 3 bajty na piksel

    lines = [
        "P3",
        f"# OneMax logo {width}x{height}, generated by scripts/make-kernel-logo.py",
        f"{width} {height}",
        "255",
    ]
    for row in range(height):
        values = []
        for x in range(width):
            i = 3 * (row * width + x)
            values.append(f"{raw[i]} {raw[i + 1]} {raw[i + 2]}")
        # Krotkie linie: pnmtologo nie ma limitu, ale czytelniej jest w piatkach pikseli.
        for start in range(0, len(values), 5):
            lines.append(" ".join(values[start:start + 5]))

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"zapisano {out} ({width}x{height})")


if __name__ == "__main__":
    main()
